'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'EN' | 'ES' | 'FR' | 'DE' | 'IT' | 'PT' | 'RU' | 'HI' | 'ZH' | 'JA';

export const LANGUAGES: { code: LanguageCode; name: string }[] = [
  { code: 'EN', name: 'English' },
  { code: 'ES', name: 'Español' },
  { code: 'FR', name: 'Français' },
  { code: 'DE', name: 'Deutsch' },
  { code: 'IT', name: 'Italiano' },
  { code: 'PT', name: 'Português' },
  { code: 'RU', name: 'Русский' },
  { code: 'HI', name: 'हिन्दी' },
  { code: 'ZH', name: '中文' },
  { code: 'JA', name: '日本語' },
];

const translations: Record<LanguageCode, Record<string, string>> = {
  EN: {
    // Nav
    'nav.services': 'Services',
    'nav.work': 'Work',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.cta': 'Start a Project',
    'nav.theme': 'Toggle Theme',
    'nav.lang': 'Select Language',

    // Footer
    'footer.cta.eyebrow': 'Start a Project',
    'footer.cta.title': 'Ready to build\nsomething great?',
    'footer.cta.btn': 'Get in touch',
    'footer.desc': 'Strategy, design, and development studio. We build what ambitious companies need to lead.',
    'footer.studio': 'Studio',
    'footer.legal': 'Legal',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.cookies': 'Cookies',
    'footer.rights': 'All rights reserved.',

    // Home
    'home.hero.eyebrow': 'Strategy, Design & Development Studio',
    'home.hero.title': 'Creative studio\nbuilt for',
    'home.hero.desc': 'Strategy, design and development. From brand identities to full-scale platforms, we build what companies need to lead.',
    'home.hero.cta.work': 'See our work',
    'home.hero.cta.project': 'Start a project',
    'home.meta.scroll': 'Scroll to explore',
    'home.hero.typewriter': 'Strategy,Development,Design,Innovation,Excellence',

    'home.services.eyebrow': 'What we do',
    'home.services.title': 'Selected areas of expertise',
    'home.services.cta': 'Explore all services',

    'home.why.eyebrow': 'Our DNA',
    'home.why.title': 'Why leading brands choose Codnexa',
    'home.why.dna1.title': 'Direct Developer Loop',
    'home.why.dna1.desc': 'No account managers. You speak directly with the engineers building your product.',
    'home.why.dna2.title': 'Business-Oriented Engineering',
    'home.why.dna2.desc': 'Code is a mechanism to drive metrics and revenue. We architect to scale alongside growth.',
    'home.why.dna3.title': 'Meticulous Transparency',
    'home.why.dna3.desc': 'Full visibility over repos, staging pipelines, and sprints. Day by day accountability.',
    'home.why.dna4.title': 'Rapid Iteration',
    'home.why.dna4.desc': 'Weekly sprint cycles with clear deliverables, feedback loops, and production deploys.',

    'home.work.eyebrow': 'Selected Work',
    'home.work.title': "Work we're proud of",
    'home.work.cta': 'View all work',

    'home.faq.eyebrow': 'FAQ',
    'home.faq.title': 'Common\nQuestions',

    'home.cta.title': "Let's build it together.",
    'home.cta.btn': 'Book a Discovery Call',

    // About
    'about.hero.eyebrow': 'About Codnexa',
    'about.hero.title': 'A technology driven\ndigital solutions company.',
    'about.intro.p1': 'Codnexa is a technology driven digital solutions company dedicated to helping businesses grow in an increasingly digital world. We combine creativity, innovation, and technology to build websites, web applications, and digital experiences that are visually appealing, user friendly, and performance focused.',
    'about.intro.p2': 'Our expertise spans website development, custom web applications, UI/UX design, e-commerce development, search engine optimization (SEO), branding, digital marketing, social media marketing, Google Ads, Meta Ads, and AI powered business solutions. Every solution is tailored to meet the unique goals of our clients while ensuring speed, security, scalability, and long-term growth.',
    'about.intro.p3': "At Codnexa, we believe that every business deserves a strong online presence. Whether you're launching a startup, expanding a growing company, or modernizing an established brand, our team delivers digital solutions that help you reach more customers, improve conversions, and build lasting relationships.",
    'about.intro.p4': 'We focus on creating responsive, SEO friendly websites and data driven marketing strategies that improve online visibility and generate measurable results. From strategy and design to development, launch, and ongoing support, we work closely with our clients to turn ideas into successful digital products.',
    'about.intro.p5': "Our commitment to quality, transparency, and innovation makes Codnexa a trusted partner for businesses looking to accelerate their digital transformation. We don't just deliver projects; we create solutions that empower brands to grow, compete, and succeed in today's fast changing digital landscape.",
    'about.stats.projects': 'Projects',
    'about.stats.years': 'Years',
    'about.stats.continents': 'Continents',
    'about.principles.eyebrow': 'Our Principles',
    'about.principles.title': 'The values that guide every decision',
    'about.principles.1.title': 'Absolute Transparency',
    'about.principles.1.desc': 'No hidden timelines or surprises. Real-time access to code repositories, sprint progress, and decision making logs.',
    'about.principles.2.title': 'Uncompromising Quality',
    'about.principles.2.desc': 'We write clean, production ready code with test coverage and design systems that scale without technical debt.',
    'about.principles.3.title': 'User Centric Design',
    'about.principles.3.desc': 'Interfaces must be beautiful, accessible, and intuitive. We design with purpose and validation.',
    'about.principles.4.title': 'Metric Driven Engineering',
    'about.principles.4.desc': 'We measure our code by business outcomes: conversion rates, page speed, and infrastructure resilience.',
    'about.team.eyebrow': 'The Team',
    'about.team.title': 'Built by people\nwho care',
    'about.team.founder1.role': 'Co-Founder & Technical Lead',
    'about.team.founder1.bio': 'Full-stack architect with 8+ years shipping production systems across fintech, SaaS, and enterprise. Previously at top tier consultancies before founding Codnexa.',
    'about.team.founder2.role': 'Co-Founder & Design Director',
    'about.team.founder2.bio': 'Product designer specialising in complex information design and conversion focused UI. Champion of accessibility and design systems.',
    'about.cta.title': "Let's build something exceptional.",
    'about.cta.desc': 'Have a project or partnership in mind? We\'d love to hear from you.',
    'about.cta.btn1': 'Start a Project',
    'about.cta.btn2': 'View our work',

    // Services
    'services.hero.eyebrow': 'Our Services',
    'services.hero.title': 'What we\noffer.',
    'services.hero.desc': 'Strategy, design and development. From brand identities to full scale platforms and software, we make what companies need to lead.',
    'services.cta.title': 'Ready to start your project?',
    'services.cta.desc': "Book a free discovery call and we'll scope out your vision together.",
    'services.cta.btn': 'Book a Discovery Call',
    'services.process.eyebrow': 'Our Process',
    'services.process.title': 'How we\nwork',
    'services.process.desc': 'Every engagement follows a structured workflow designed for clarity, speed, and quality.',

    // Portfolio
    'portfolio.hero.eyebrow': 'Selected Work',
    'portfolio.hero.title': 'Case studies &\ndigital platforms.',
    'portfolio.hero.desc': 'We collaborate with ambitious startups and world-leading brands to engineer clean, performant, and high-converting systems.',
    'portfolio.testimonials.eyebrow': 'Endorsements',
    'portfolio.testimonials.title': 'What clients\nsay about us',
    'portfolio.testimonials.desc': 'We measure success by the outcomes we drive for our clients, not just by shipping code.',

    // Contact
    'contact.hero.eyebrow': 'Contact Us',
    'contact.hero.title': 'Get in\ntouch',
    'contact.hero.desc': 'Ready to transform your digital experience? Fill out the brief or select a slot for a direct scoping consultation.',
    'contact.info.office': 'Office',
    'contact.info.hours': 'Hours',
    'contact.info.hours.val': 'Mon – Fri, 9am – 6pm',
    'contact.tabs.brief': 'Project Brief',
    'contact.tabs.call': 'Book a Call',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Your Email',
    'contact.form.focus': 'Project Focus',
    'contact.form.focus.placeholder': 'Select a category...',
    'contact.form.budget': 'Estimated Budget',
    'contact.form.message': 'Project Details',
    'contact.form.message.placeholder': 'Tell us about your project, goals, timeline...',
    'contact.form.submit': 'Send Inquiry',
    'contact.form.success.title': 'Thank You',
    'contact.form.success.desc': 'Your project brief has been received. Our team will review it and get back to you within 24 hours.',
    'contact.form.success.btn': 'Send another message',
    'contact.book.timezone': 'Your Timezone',
    'contact.book.select': 'Select Date & Time',
    'contact.book.submit': 'Confirm Call Booking',
    'contact.book.success.title': 'Booking Confirmed!',
    'contact.book.success.desc': 'Your discovery call is scheduled for',
  },
  ES: {
    // Nav
    'nav.services': 'Servicios',
    'nav.work': 'Trabajos',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.cta': 'Iniciar Proyecto',
    'nav.theme': 'Cambiar Tema',
    'nav.lang': 'Seleccionar Idioma',

    // Footer
    'footer.cta.eyebrow': 'Iniciar un Proyecto',
    'footer.cta.title': '¿Listo para construir\nalgo grande?',
    'footer.cta.btn': 'Ponte en contacto',
    'footer.desc': 'Estudio de estrategia, diseño y desarrollo. Creamos lo que las empresas ambiciosas necesitan para liderar.',
    'footer.studio': 'Estudio',
    'footer.legal': 'Legal',
    'footer.contact': 'Contacto',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Uso',
    'footer.cookies': 'Cookies',
    'footer.rights': 'Todos los derechos reservados.',

    // Home
    'home.hero.eyebrow': 'Estudio de Estrategia, Diseño y Desarrollo',
    'home.hero.title': 'Estudio creativo\ncreado para',
    'home.hero.desc': 'Estrategia, diseño y desarrollo. Desde identidades de marca hasta plataformas a gran escala: construimos lo que las empresas necesitan para liderar.',
    'home.hero.cta.work': 'Ver nuestro trabajo',
    'home.hero.cta.project': 'Iniciar un proyecto',
    'home.meta.scroll': 'Desplazarse para explorar',
    'home.hero.typewriter': 'Estrategia,Desarrollo,Diseño,Innovación,Excelencia',

    'home.services.eyebrow': 'Qué hacemos',
    'home.services.title': 'Áreas de especialización seleccionadas',
    'home.services.cta': 'Explorar todos los servicios',

    'home.why.eyebrow': 'Nuestro ADN',
    'home.why.title': 'Por qué las marcas líderes eligen Codnexa',
    'home.why.dna1.title': 'Canal Directo con Desarrolladores',
    'home.why.dna1.desc': 'Sin intermediarios. Hablas directamente con los ingenieros que construyen tu producto.',
    'home.why.dna2.title': 'Ingeniería Orientada a Negocios',
    'home.why.dna2.desc': 'El código es un mecanismo para impulsar métricas y ventas. Diseñamos para escalar con tu crecimiento.',
    'home.why.dna3.title': 'Transparencia Meticulosa',
    'home.why.dna3.desc': 'Visibilidad total sobre repositorios, pipelines de prueba y sprints. Responsabilidad diaria.',
    'home.why.dna4.title': 'Iteración Rápida',
    'home.why.dna4.desc': 'Ciclos de sprint semanales con entregables claros, bucles de retroalimentación y despliegues en producción.',

    'home.work.eyebrow': 'Trabajos Seleccionados',
    'home.work.title': 'Trabajos de los que estamos orgullosos',
    'home.work.cta': 'Ver todos los trabajos',

    'home.faq.eyebrow': 'Preguntas frecuentes',
    'home.faq.title': 'Preguntas\nComunes',

    'home.cta.title': 'Construyámoslo juntos.',
    'home.cta.btn': 'Reservar una llamada de descubrimiento',

    // About
    'about.hero.eyebrow': 'Sobre Codnexa',
    'about.hero.title': 'Un estudio que entrega\ntrabajos excepcionales.',
    'about.intro.p1': 'Codnexa es un estudio digital boutique fundado bajo la creencia de que el gran software es la intersección de estrategia, diseño y tecnología, no una decisión de compromiso.',
    'about.intro.p2': 'Somos un equipo pequeño y senior. Sin desarrolladores junior aprendiendo con tu proyecto. Sin gestores de cuentas como filtro. Solo ingenieros y diseñadores experimentados que cuidan cada producto.',
    'about.intro.p3': 'Fundado en 2016, nos hemos asociado con startups y empresas consolidadas en fintech, salud, comercio electrónico y SaaS, siempre con el mismo compromiso de calidad.',
    'about.stats.projects': 'Proyectos',
    'about.stats.years': 'Años',
    'about.stats.continents': 'Continentes',
    'about.principles.eyebrow': 'Nuestros Principios',
    'about.principles.title': 'Los valores que guían cada decisión',
    'about.principles.1.title': 'Transparencia Absoluta',
    'about.principles.1.desc': 'Sin sorpresas ni plazos ocultos. Acceso en tiempo real a los repositorios de código, sprints y registros de decisión.',
    'about.principles.2.title': 'Calidad sin Concesiones',
    'about.principles.2.desc': 'Escribimos código limpio y listo para producción con cobertura de pruebas y sistemas de diseño escalables.',
    'about.principles.3.title': 'Diseño Centrado en el Usuario',
    'about.principles.3.desc': 'Las interfaces deben ser hermosas, accesibles e intuitivas. Diseñamos con propósito y validación.',
    'about.principles.4.title': 'Ingeniería Basada en Métricas',
    'about.principles.4.desc': 'Medimos nuestro código por resultados de negocio: tasas de conversión, velocidad de carga y resistencia técnica.',
    'about.team.eyebrow': 'El Equipo',
    'about.team.title': 'Construido por personas\nque aman lo que hacen',
    'about.team.founder1.role': 'Co-Fundador y Director Técnico',
    'about.team.founder1.bio': 'Arquitecto full-stack con más de 8 años entregando sistemas en fintech, SaaS y corporaciones. Anteriormente en consultoras de primer nivel.',
    'about.team.founder2.role': 'Co-Fundadora y Directora de Diseño',
    'about.team.founder2.bio': 'Diseñadora de productos especializada en diseño de información compleja e interfaces enfocadas en conversión y accesibilidad.',
    'about.cta.title': 'Construyamos algo excepcional.',
    'about.cta.desc': '¿Tienes un proyecto en mente? Nos encantaría escucharte.',
    'about.cta.btn1': 'Iniciar un Proyecto',
    'about.cta.btn2': 'Ver nuestro trabajo',

    // Services
    'services.hero.eyebrow': 'Nuestros Servicios',
    'services.hero.title': 'Lo que\nofrecemos.',
    'services.hero.desc': 'Estrategia, diseño y desarrollo. Desde identidades de marca hasta plataformas a gran escala: creamos lo necesario para liderar.',
    'services.cta.title': '¿Listo para iniciar tu proyecto?',
    'services.cta.desc': 'Reserva una llamada de descubrimiento gratuita y definiremos tu visión juntos.',
    'services.cta.btn': 'Reservar llamada de descubrimiento',
    'services.process.eyebrow': 'Nuestro Proceso',
    'services.process.title': 'Cómo\ntrabajamos',
    'services.process.desc': 'Cada colaboración sigue un flujo de trabajo estructurado diseñado para brindar claridad, velocidad y calidad.',

    // Portfolio
    'portfolio.hero.eyebrow': 'Trabajos Seleccionados',
    'portfolio.hero.title': 'Casos de estudio y\nplataformas digitales.',
    'portfolio.hero.desc': 'Colaboramos con startups ambiciosas y marcas líderes para construir sistemas limpios, rápidos y de alta conversión.',
    'portfolio.testimonials.eyebrow': 'Testimonios',
    'portfolio.testimonials.title': 'Lo que nuestros\nclientes opinan',
    'portfolio.testimonials.desc': 'Medimos el éxito por los resultados de negocio de nuestros clientes, no solo por entregar código.',

    // Contact
    'contact.hero.eyebrow': 'Contacto',
    'contact.hero.title': 'Ponte en\ncontacto',
    'contact.hero.desc': '¿Listo para transformar tu experiencia digital? Rellena el formulario o reserva una sesión para una consulta directa.',
    'contact.info.office': 'Oficina',
    'contact.info.hours': 'Horario',
    'contact.info.hours.val': 'Lun – Vie, 9am – 6pm',
    'contact.tabs.brief': 'Formulario de Proyecto',
    'contact.tabs.call': 'Reservar Llamada',
    'contact.form.name': 'Tu Nombre',
    'contact.form.email': 'Tu Correo',
    'contact.form.focus': 'Enfoque del Proyecto',
    'contact.form.focus.placeholder': 'Selecciona una categoría...',
    'contact.form.focus.brand': 'Marca y UI/UX',
    'contact.form.focus.web': 'Desarrollo Web',
    'contact.form.focus.mobile': 'Apps Móviles',
    'contact.form.focus.full': 'Desarrollo Completo',
    'contact.form.budget': 'Presupuesto Estimado',
    'contact.form.message': 'Detalles del Proyecto',
    'contact.form.message.placeholder': 'Cuéntanos sobre tu proyecto, objetivos, plazos...',
    'contact.form.submit': 'Enviar Mensaje',
    'contact.form.success.title': '¡Gracias!',
    'contact.form.success.desc': 'Hemos recibido tus detalles. Nuestro equipo revisará el informe y te responderá en menos de 24 horas.',
    'contact.form.success.btn': 'Enviar otro mensaje',
    'contact.book.timezone': 'Tu Zona Horaria',
    'contact.book.select': 'Seleccionar Fecha y Hora',
    'contact.book.submit': 'Confirmar Reserva de Llamada',
    'contact.book.success.title': '¡Llamada Reservada!',
    'contact.book.success.desc': 'Tu llamada de descubrimiento está programada para',
  },
  FR: {
    // Nav
    'nav.services': 'Services',
    'nav.work': 'Projets',
    'nav.about': 'À Propos',
    'nav.contact': 'Contact',
    'nav.cta': 'Lancer un Projet',
    'nav.theme': 'Changer le Thème',
    'nav.lang': 'Choisir la Langue',

    // Footer
    'footer.cta.eyebrow': 'Lancer un Projet',
    'footer.cta.title': 'Prêt à construire\nquelque chose de grand?',
    'footer.cta.btn': 'Prendre contact',
    'footer.desc': 'Studio de stratégie, de design et de développement. Nous créons ce dont les entreprises ambitieuses ont besoin pour mener.',
    'footer.studio': 'Studio',
    'footer.legal': 'Légal',
    'footer.contact': 'Contact',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': "Conditions d'Utilisation",
    'footer.cookies': 'Cookies',
    'footer.rights': 'Tous droits réservés.',

    // Home
    'home.hero.eyebrow': 'Studio de Stratégie, Design & Développement',
    'home.hero.title': 'Studio créatif\nconçu pour',
    'home.hero.desc': 'Stratégie, design et développement. Des identités de marque aux plateformes complexes : nous créons ce dont les leaders ont besoin.',
    'home.hero.cta.work': 'Voir nos projets',
    'home.hero.cta.project': 'Lancer un projet',
    'home.meta.scroll': 'Faire défiler pour explorer',
    'home.hero.typewriter': 'Stratégie,Développement,Conception,Innovation,Excellence',

    'home.services.eyebrow': 'Notre expertise',
    'home.services.title': 'Domaines de compétences sélectionnés',
    'home.services.cta': 'Explorer tous les services',

    'home.why.eyebrow': 'Notre ADN',
    'home.why.title': 'Pourquoi les grandes marques choisissent Codnexa',
    'home.why.dna1.title': 'Échange Direct avec Développeurs',
    'home.why.dna1.desc': 'Pas de gestionnaire de compte. Vous parlez directement aux ingénieurs qui créent votre produit.',
    'home.why.dna2.title': 'Ingénierie Axée Business',
    'home.why.dna2.desc': 'Le code est un moyen de maximiser vos objectifs et vos revenus. Nous concevons pour la croissance.',
    'home.why.dna3.title': 'Transparence Rigoureuse',
    'home.why.dna3.desc': 'Accès total aux dépôts, aux pipelines de test et aux sprints. Responsabilité quotidienne.',
    'home.why.dna4.title': 'Itérations Rapides',
    'home.why.dna4.desc': 'Des cycles de sprints hebdomadaires avec des livrables clairs, des retours continus et des déploiements réels.',

    'home.work.eyebrow': 'Projets Sélectionnés',
    'home.work.title': 'Les réalisations dont nous sommes fiers',
    'home.work.cta': 'Voir tous nos projets',

    'home.faq.eyebrow': 'FAQ',
    'home.faq.title': 'Questions\nFréquentes',

    'home.cta.title': 'Construisons ensemble.',
    'home.cta.btn': 'Réserver un appel exploratoire',

    // About
    'about.hero.eyebrow': 'À Propos de Codnexa',
    'about.hero.title': 'Un studio qui livre\nun travail exceptionnel.',
    'about.intro.p1': 'Codnexa est un studio digital boutique fondé sur la conviction que le grand logiciel est le produit de la stratégie, du design et du code, sans aucun compromis.',
    'about.intro.p2': 'Nous sommes une petite équipe senior. Pas de développeurs juniors qui se forment sur votre projet. Pas de gestionnaires de compte intermédiaires. Uniquement des experts.',
    'about.intro.p3': 'Fondé en 2016, nous accompagnons des startups, scaleups et grandes entreprises dans la fintech, la santé, le e-commerce et le SaaS.',
    'about.stats.projects': 'Projets',
    'about.stats.years': 'Années',
    'about.stats.continents': 'Continents',
    'about.principles.eyebrow': 'Nos Principes',
    'about.principles.title': 'Les valeurs derrière chaque projet',
    'about.principles.1.title': 'Transparence Absolue',
    'about.principles.1.desc': 'Aucune surprise. Accès complet en temps réel aux dépôts de code, sprints et décisions.',
    'about.principles.2.title': 'Qualité sans Concession',
    'about.principles.2.desc': 'Nous écrivons du code propre, robuste et documenté avec une excellente couverture de tests.',
    'about.principles.3.title': 'Design Axé Utilisateur',
    'about.principles.3.desc': 'Les interfaces doivent être belles, intuitives et accessibles. Nous concevons avec sens et validation.',
    'about.principles.4.title': 'Efficacité Produit',
    'about.principles.4.desc': 'Nous jugeons la qualité de notre travail par vos métriques : taux de conversion, vitesse et résilience.',
    'about.team.eyebrow': 'L’Équipe',
    'about.team.title': 'Créé par des passionnés\ndu code et du design',
    'about.team.founder1.role': 'Co-Fondateur & Directeur Technique',
    'about.team.founder1.bio': 'Architecte full-stack avec 8+ ans d’expérience dans le SaaS et la fintech. A travaillé dans des cabinets de conseil renommés.',
    'about.team.founder2.role': 'Co-Fondatrice & Directrice Artistique',
    'about.team.founder2.bio': 'Designer produit spécialisée dans les parcours utilisateurs complexes et les designs d’interfaces à fort taux de conversion.',
    'about.cta.title': 'Bâtissons quelque chose d’exceptionnel.',
    'about.cta.desc': 'Vous avez une idée ou un projet ? Nous serions ravis d’en parler.',
    'about.cta.btn1': 'Lancer un Projet',
    'about.cta.btn2': 'Voir nos projets',

    // Services
    'services.hero.eyebrow': 'Nos Services',
    'services.hero.title': 'Ce que nous\noffrons.',
    'services.hero.desc': 'Stratégie, design et code. Des identités graphiques aux systèmes cloud complexes, nous livrons de la valeur.',
    'services.cta.title': 'Prêt à démarrer votre projet ?',
    'services.cta.desc': 'Réservez un appel gratuit et explorons votre projet ensemble.',
    'services.cta.btn': 'Réserver un appel exploratoire',
    'services.process.eyebrow': 'Notre Processus',
    'services.process.title': 'Comment nous\ntravaillons',
    'services.process.desc': 'Chaque projet suit une méthodologie claire et structurée assurant vitesse et qualité.',

    // Portfolio
    'portfolio.hero.eyebrow': 'Réalisations',
    'portfolio.hero.title': 'Études de cas et\nplateformes digitales.',
    'portfolio.hero.desc': 'Nous créons des applications web et mobiles rapides, performantes et optimisées pour les leaders du marché.',
    'portfolio.testimonials.eyebrow': 'Avis Clients',
    'portfolio.testimonials.title': 'Ce que nos\nclients racontent',
    'portfolio.testimonials.desc': 'Nous mesurons notre valeur par le succès de votre produit, pas seulement par les livraisons.',

    // Contact
    'contact.hero.eyebrow': 'Nous Contacter',
    'contact.hero.title': 'Prendre\ncontact',
    'contact.hero.desc': 'Prêt à transformer votre produit digital ? Remplissez le brief ou réservez un créneau directement.',
    'contact.info.office': 'Bureaux',
    'contact.info.hours': 'Horaires',
    'contact.info.hours.val': 'Lun – Ven, 9h – 18h',
    'contact.tabs.brief': 'Brief Projet',
    'contact.tabs.call': 'Réserver un Appel',
    'contact.form.name': 'Votre Nom',
    'contact.form.email': 'Votre Email',
    'contact.form.focus': 'Type de Projet',
    'contact.form.focus.placeholder': 'Choisissez une option...',
    'contact.form.budget': 'Budget Estimé',
    'contact.form.message': 'Détails du Projet',
    'contact.form.message.placeholder': 'Présentez-nous votre projet, vos objectifs, vos délais...',
    'contact.form.submit': 'Envoyer la Demande',
    'contact.form.success.title': 'Merci !',
    'contact.form.success.desc': 'Votre brief de projet a bien été reçu. Notre équipe l’analysera et vous répondra sous 24 heures.',
    'contact.form.success.btn': 'Envoyer un autre message',
    'contact.book.timezone': 'Fuseau Horaire',
    'contact.book.select': 'Sélectionner Date & Heure',
    'contact.book.submit': 'Confirmer le Rendez-vous',
    'contact.book.success.title': 'Rendez-vous Confirmé !',
    'contact.book.success.desc': 'Votre appel est programmé pour le',
  },
  DE: {
    // Nav
    'nav.services': 'Leistungen',
    'nav.work': 'Projekte',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    'nav.cta': 'Projekt starten',
    'nav.theme': 'Farbschema umschalten',
    'nav.lang': 'Sprache wählen',

    // Footer
    'footer.cta.eyebrow': 'Projekt starten',
    'footer.cta.title': 'Bereit für etwas\nGroßartiges?',
    'footer.cta.btn': 'Kontakt aufnehmen',
    'footer.desc': 'Studio für Strategie, Design und Entwicklung. Wir bauen, was ambitionierte Unternehmen zum Erfolg brauchen.',
    'footer.studio': 'Studio',
    'footer.legal': 'Rechtliches',
    'footer.contact': 'Kontakt',
    'footer.privacy': 'Datenschutzerklärung',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.cookies': 'Cookies',
    'footer.rights': 'Alle Rechte vorbehalten.',

    // Home
    'home.hero.eyebrow': 'Studio für Strategie, Design & Entwicklung',
    'home.hero.title': 'Kreativstudio\ngebaut für',
    'home.hero.desc': 'Strategie, Design und Entwicklung. Von Markenidentitäten bis hin zu komplexen Softwareplattformen – wir schaffen digitale Marktführer.',
    'home.hero.cta.work': 'Unsere Arbeit sehen',
    'home.hero.cta.project': 'Projekt starten',
    'home.meta.scroll': 'Scrollen zum Erkunden',
    'home.hero.typewriter': 'Strategie,Entwicklung,Design,Innovation,Exzellenz',

    'home.services.eyebrow': 'Unsere Expertise',
    'home.services.title': 'Ausgewählte Kompetenzbereiche',
    'home.services.cta': 'Alle Leistungen ansehen',

    'home.why.eyebrow': 'Unsere DNA',
    'home.why.title': 'Warum führende Marken sich für Codnexa entscheiden',
    'home.why.dna1.title': 'Direkter Entwickler-Kontakt',
    'home.why.dna1.desc': 'Keine Account Manager. Sie sprechen direkt mit den Software-Ingenieuren, die Ihr Produkt bauen.',
    'home.why.dna2.title': 'Business-Fokus im Code',
    'home.why.dna2.desc': 'Code ist kein Selbstzweck, sondern treibt Kennzahlen und Umsatz. Wir entwickeln skalierbare Lösungen.',
    'home.why.dna3.title': 'Absolute Transparenz',
    'home.why.dna3.desc': 'Voller Zugriff auf Repositories, Test-Pipelines und Sprints. Tägliche Verantwortlichkeit.',
    'home.why.dna4.title': 'Schnelle Iterationen',
    'home.why.dna4.desc': 'Wöchentliche Sprints mit klaren Ergebnissen, Feedbackrunden und echten Deployments.',

    'home.work.eyebrow': 'Ausgewählte Projekte',
    'home.work.title': 'Projekte, auf die wir stolz sind',
    'home.work.cta': 'Alle Projekte anzeigen',

    'home.faq.eyebrow': 'FAQ',
    'home.faq.title': 'Häufige\nFragen',

    'home.cta.title': 'Lassen Sie uns zusammen arbeiten.',
    'home.cta.btn': 'Kostenloses Erstgespräch buchen',

    // About
    'about.hero.eyebrow': 'Über Codnexa',
    'about.hero.title': 'Ein Studio, das\nExzellenz liefert.',
    'about.intro.p1': 'Codnexa ist ein Boutique-Digitalstudio. Wir glauben, dass herausragende Software das Zusammenspiel aus Strategie, Design und Engineering ist – ohne Kompromisse.',
    'about.intro.p2': 'Wir sind ein kleines, erfahrenes Senior-Team. Keine Junioren, die an Ihrem Projekt lernen. Keine bürokratischen Hürden. Nur erfahrene Köpfe, die Ihr Produkt lieben.',
    'about.intro.p3': 'Gegründet im Jahr 2016 haben wir als verlässlicher Partner Start-ups und etablierte Unternehmen in Fintech, Healthcare, E-Commerce und SaaS skaliert.',
    'about.stats.projects': 'Projekte',
    'about.stats.years': 'Jahre',
    'about.stats.continents': 'Kontinente',
    'about.principles.eyebrow': 'Unsere Prinzipien',
    'about.principles.title': 'Die Werte hinter jedem Handeln',
    'about.principles.1.title': 'Absolute Transparenz',
    'about.principles.1.desc': 'Keine versteckten Deadlines. Voller Echtzeitzugriff auf Code repositories, Fortschritte und Entscheidungen.',
    'about.principles.2.title': 'Kompromisslose Qualität',
    'about.principles.2.desc': 'Wir schreiben sauberen, getesteten Code und etablieren langlebige Design-Systeme ohne technischen Ballast.',
    'about.principles.3.title': 'Nutzerzentriertes Design',
    'about.principles.3.desc': 'Interfaces müssen schön, intuitiv und barrierefrei sein. Jedes Detail hat einen Sinn.',
    'about.principles.4.title': 'Wertschöpfung im Fokus',
    'about.principles.4.desc': 'Wir messen die Qualität an echten Metriken: Conversion-Rates, Pagespeed und System-Verfügbarkeit.',
    'about.team.eyebrow': 'Das Team',
    'about.team.title': 'Gebaut von Menschen,\nden Qualität am Herzen liegt',
    'about.team.founder1.role': 'Mitgründer & Tech-Lead',
    'about.team.founder1.bio': 'Full-Stack-Architekt mit 8+ Jahren Erfahrung im Entwickeln anspruchsvoller Systeme in Fintech und SaaS.',
    'about.team.founder2.role': 'Mitgründerin & Design-Direktorin',
    'about.team.founder2.bio': 'Product Designerin spezialisiert auf anspruchsvolle Informationsarchitektur und conversion-starke Interfaces.',
    'about.cta.title': 'Lassen Sie uns etwas Besonderes bauen.',
    'about.cta.desc': 'Haben Sie ein Projekt vor Augen? Wir freuen uns auf das Gespräch.',
    'about.cta.btn1': 'Projekt starten',
    'about.cta.btn2': 'Projekte ansehen',

    // Services
    'services.hero.eyebrow': 'Unsere Leistungen',
    'services.hero.title': 'Was wir\nanbieten.',
    'services.hero.desc': 'Strategie, Design und Code. Von Corporate Design bis hin zu komplexer Server-Infrastruktur – wir machen Marken stark.',
    'services.cta.title': 'Bereit für Ihr Projekt?',
    'services.cta.desc': 'Buchen Sie ein kostenloses Erstgespräch, um Ihre Vision Realität werden zu lassen.',
    'services.cta.btn': 'Kostenloses Erstgespräch buchen',
    'services.process.eyebrow': 'Unser Ablauf',
    'services.process.title': 'Wie wir\narbeiten',
    'services.process.desc': 'Jedes Projekt folgt einem klar strukturierten Ablauf für maximale Effizienz und Transparenz.',

    // Portfolio
    'portfolio.hero.eyebrow': 'Referenzen',
    'portfolio.hero.title': 'Fallstudien & digitale\nPlattformen.',
    'portfolio.hero.desc': 'Wir arbeiten mit ambitionierten Marken zusammen, um saubere, hochperformante Digitalsysteme zu programmieren.',
    'portfolio.testimonials.eyebrow': 'Kundenstimmen',
    'portfolio.testimonials.title': 'Was unsere\nPartner sagen',
    'portfolio.testimonials.desc': 'Erfolg messen wir nicht in geschriebenen Codezeilen, sondern an den realen Zielen unserer Partner.',

    // Contact
    'contact.hero.eyebrow': 'Kontakt',
    'contact.hero.title': 'Lassen Sie uns\nschreiben',
    'contact.hero.desc': 'Bereit für den nächsten Schritt? Füllen Sie das Briefing aus oder buchen Sie direkt ein Gespräch.',
    'contact.info.office': 'Studio',
    'contact.info.hours': 'Erreichbarkeit',
    'contact.info.hours.val': 'Mo – Fr, 9:00 – 18:00 Uhr',
    'contact.tabs.brief': 'Projekt-Briefing',
    'contact.tabs.call': 'Gespräch buchen',
    'contact.form.name': 'Ihr Name',
    'contact.form.email': 'E-Mail-Adresse',
    'contact.form.focus': 'Projektschwerpunkt',
    'contact.form.focus.placeholder': 'Bereich auswählen...',
    'contact.form.budget': 'Geschätztes Budget',
    'contact.form.message': 'Projektbeschreibung',
    'contact.form.message.placeholder': 'Erzählen Sie uns von Ihren Zielen, Deadlines und Ideen...',
    'contact.form.submit': 'Anfrage absenden',
    'contact.form.success.title': 'Vielen Dank!',
    'contact.form.success.desc': 'Ihr Projekt-Briefing ist eingegangen. Wir melden uns innerhalb von 24 Stunden bei Ihnen.',
    'contact.form.success.btn': 'Weitere Anfrage senden',
    'contact.book.timezone': 'Ihre Zeitzone',
    'contact.book.select': 'Datum & Uhrzeit wählen',
    'contact.book.submit': 'Termin bestätigen',
    'contact.book.success.title': 'Termin bestätigt!',
    'contact.book.success.desc': 'Ihr Erstgespräch wurde erfolgreich gebucht für',
  },
  IT: {
    // Nav
    'nav.services': 'Servizi',
    'nav.work': 'Progetti',
    'nav.about': 'Studio',
    'nav.contact': 'Contatti',
    'nav.cta': 'Avvia Progetto',
    'nav.theme': 'Cambia Tema',
    'nav.lang': 'Seleziona Lingua',

    // Footer
    'footer.cta.eyebrow': 'Avvia un Progetto',
    'footer.cta.title': 'Pronto a creare\nqualcosa di grande?',
    'footer.cta.btn': 'Contattaci',
    'footer.desc': 'Studio di strategia, design e sviluppo. Creiamo ciò di cui le aziende ambiziose hanno bisogno per guidare il mercato.',
    'footer.studio': 'Studio',
    'footer.legal': 'Legale',
    'footer.contact': 'Contatti',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Termini di Servizio',
    'footer.cookies': 'Cookie Policy',
    'footer.rights': 'Tutti i diritti riservati.',

    // Home
    'home.hero.eyebrow': 'Studio di Strategia, Design e Sviluppo',
    'home.hero.title': 'Studio creativo\ncreato per',
    'home.hero.desc': 'Strategia, design e sviluppo. Da identità di brand a piattaforme complesse: realizziamo ciò di cui hai bisogno per essere leader.',
    'home.hero.cta.work': 'Vedi i nostri lavori',
    'home.hero.cta.project': 'Avvia un progetto',
    'home.meta.scroll': 'Scorri per esplorare',
    'home.hero.typewriter': 'Strategia,Sviluppo,Progettazione,Innovazione,Eccellenza',

    'home.services.eyebrow': 'Cosa Facciamo',
    'home.services.title': 'Aree selezionate di competenza',
    'home.services.cta': 'Esplora tutti i servizi',

    'home.why.eyebrow': 'Il Nostro DNA',
    'home.why.title': 'Perché i brand leader scelgono Codnexa',
    'home.why.dna1.title': 'Contatto Diretto Sviluppatori',
    'home.why.dna1.desc': 'Nessun account manager intermediario. Parli direttamente con chi scrive il codice del tuo prodotto.',
    'home.why.dna2.title': 'Ingegneria Orientata al Business',
    'home.why.dna2.desc': 'Il codice è uno strumento per aumentare le vendite e scalare. Sviluppiamo pensando alla crescita.',
    'home.why.dna3.title': 'Trasparenza Meticolosa',
    'home.why.dna3.desc': 'Accesso completo in tempo reale a repository, pipeline di test e sprint. Feedback giornalieri.',
    'home.why.dna4.title': 'Iterazione Rapida',
    'home.why.dna4.desc': 'Sprint settimanali con obiettivi chiari, feedback continui e rilasci in produzione rapidi.',

    'home.work.eyebrow': 'Progetti Selezionati',
    'home.work.title': 'Lavori di cui andiamo fieri',
    'home.work.cta': 'Vedi tutti i progetti',

    'home.faq.eyebrow': 'FAQ',
    'home.faq.title': 'Domande\nFrequenti',

    'home.cta.title': 'Costruiamolo insieme.',
    'home.cta.btn': 'Prenota una chiamata conoscitiva',

    // About
    'about.hero.eyebrow': 'Chi Siamo',
    'about.hero.title': 'Uno studio che crea\nprodotti eccezionali.',
    'about.intro.p1': 'Codnexa è uno studio digitale boutique fondato sulla convinzione che il software debba unire strategia, design e tecnologia, senza compromessi.',
    'about.intro.p2': 'Siamo un team senior compatto. Nessun programmatore junior che fa pratica sul tuo progetto. Dialogo diretto e decisioni rapide.',
    'about.intro.p3': 'Fondati nel 2016, abbiamo lavorato a fianco di startup e imprese leader nei settori fintech, digital-health, e-commerce e SaaS.',
    'about.stats.projects': 'Progetti',
    'about.stats.years': 'Anni',
    'about.stats.continents': 'Continenti',
    'about.principles.eyebrow': 'I Nostri Principi',
    'about.principles.title': 'I valori che guidano ogni nostra scelta',
    'about.principles.1.title': 'Trasparenza Totale',
    'about.principles.1.desc': 'Nessun costo nascosto o ritardo. Tracciamento in tempo reale del codice e degli avanzamenti del progetto.',
    'about.principles.2.title': 'Qualità Senza Compromessi',
    'about.principles.2.desc': 'Codice pulito, pronto per la produzione, coperto da test automatizzati e basato su design system moderni.',
    'about.principles.3.title': 'Design Utente Prima di Tutto',
    'about.principles.3.desc': 'Le interfacce devono essere belle, accessibili e intuitive. Progettiamo con uno scopo preciso.',
    'about.principles.4.title': 'Risultati di Business',
    'about.principles.4.desc': 'Valutiamo le nostre performance in base ai tuoi risultati: conversioni, velocità e affidabilità infrastrutturale.',
    'about.team.eyebrow': 'Il Team',
    'about.team.title': 'Creato da persone che\namano la qualità',
    'about.team.founder1.role': 'Co-Fondatore & Tech Lead',
    'about.team.founder1.bio': 'Architetto full-stack con oltre 8 anni di esperienza in fintech, SaaS e cloud. Ha lavorato in grandi realtà consulenziali.',
    'about.team.founder2.role': 'Co-Fondatrice & Design Director',
    'about.team.founder2.bio': 'Product designer esperta in interfacce complesse, design system e UI orientata alla conversione.',
    'about.cta.title': 'Creiamo qualcosa di straordinario.',
    'about.cta.desc': 'Hai un progetto da realizzare? Raccontaci la tua idea.',
    'about.cta.btn1': 'Inizia un Progetto',
    'about.cta.btn2': 'Vedi i nostri progetti',

    // Services
    'services.hero.eyebrow': 'Servizi',
    'services.hero.title': 'La nostra\nofferta.',
    'services.hero.desc': 'Strategia, design e sviluppo. Dalle linee guida di brand alle infrastrutture server scalabili: ti aiutiamo a crescere.',
    'services.cta.title': 'Pronto a partire con il progetto?',
    'services.cta.desc': 'Prenota una chiamata gratuita ed esploriamo la tua visione.',
    'services.cta.btn': 'Prenota una chiamata conoscitiva',
    'services.process.eyebrow': 'Il Processo',
    'services.process.title': 'Come\nlavoriamo',
    'services.process.desc': 'Seguiamo una roadmap strutturata volta a garantire massima qualità, velocità ed efficienza.',

    // Portfolio
    'portfolio.hero.eyebrow': 'Portfolio',
    'portfolio.hero.title': 'Casi studio e\npiattaforme digitali.',
    'portfolio.hero.desc': 'Sviluppiamo soluzioni rapide, affidabili e ad alta conversione per brand ambiziosi.',
    'portfolio.testimonials.eyebrow': 'Testimonianze',
    'portfolio.testimonials.title': 'Dicono di noi',
    'portfolio.testimonials.desc': 'Misuriamo il successo dal valore che generiamo per il business dei nostri clienti.',

    // Contact
    'contact.hero.eyebrow': 'Contatti',
    'contact.hero.title': 'Parla con\nlo studio',
    'contact.hero.desc': 'Pronto a portare il tuo prodotto al livello successivo? Compila il form o prenota una chiamata diretta.',
    'contact.info.office': 'Ufficio',
    'contact.info.hours': 'Orari',
    'contact.info.hours.val': 'Lun – Ven, 9:00 – 18:00',
    'contact.tabs.brief': 'Invia Briefing',
    'contact.tabs.call': 'Prenota Slot',
    'contact.form.name': 'Il Tuo Nome',
    'contact.form.email': 'Tua Email',
    'contact.form.focus': 'Focus Progetto',
    'contact.form.focus.placeholder': 'Seleziona una categoria...',
    'contact.form.budget': 'Budget Stimato',
    'contact.form.message': 'Dettagli Progetto',
    'contact.form.message.placeholder': 'Parlaci delle tue necessità, tempistiche, obiettivi...',
    'contact.form.submit': 'Invia Richiesta',
    'contact.form.success.title': 'Grazie!',
    'contact.form.success.desc': 'Abbiamo ricevuto la tua richiesta. Ti risponderemo entro 24 ore lavorative.',
    'contact.form.success.btn': 'Invia un altro messaggio',
    'contact.book.timezone': 'Fuso Orario',
    'contact.book.select': 'Scegli Giorno e Ora',
    'contact.book.submit': 'Conferma Appuntamento',
    'contact.book.success.title': 'Appuntamento Confermato!',
    'contact.book.success.desc': 'La tua chiamata di scoperta è fissata per il giorno',
  },
  PT: {
    // Nav
    'nav.services': 'Serviços',
    'nav.work': 'Projetos',
    'nav.about': 'Sobre',
    'nav.contact': 'Contato',
    'nav.cta': 'Iniciar Projeto',
    'nav.theme': 'Alternar Tema',
    'nav.lang': 'Escolher Idioma',

    // Footer
    'footer.cta.eyebrow': 'Iniciar um Projeto',
    'footer.cta.title': 'Pronto para construir\nalgo incrível?',
    'footer.cta.btn': 'Entre em contato',
    'footer.desc': 'Estúdio de estratégia, design e desenvolvimento. Construímos o que as marcas ambiciosas precisam para liderar.',
    'footer.studio': 'Estúdio',
    'footer.legal': 'Legal',
    'footer.contact': 'Contato',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos de Uso',
    'footer.cookies': 'Cookies',
    'footer.rights': 'Todos os direitos reservados.',

    // Home
    'home.hero.eyebrow': 'Estúdio de Estratégia, Design & Desenvolvimento',
    'home.hero.title': 'Estúdio criativo\nfeito para',
    'home.hero.desc': 'Estratégia, design e desenvolvimento. De identidades de marca a plataformas complexas: criamos o que as empresas precisam para liderar.',
    'home.hero.cta.work': 'Ver nosso trabalho',
    'home.hero.cta.project': 'Iniciar um projeto',
    'home.meta.scroll': 'Role para explorar',
    'home.hero.typewriter': 'Estratégia,Desenvolvimento,Design,Inovação,Excelência',

    'home.services.eyebrow': 'O que fazemos',
    'home.services.title': 'Áreas de especialização selecionadas',
    'home.services.cta': 'Explorar todos os serviços',

    'home.why.eyebrow': 'Nosso ADN',
    'home.why.title': 'Por que marcas líderes escolhem a Codnexa',
    'home.why.dna1.title': 'Canal Direto com Desenvolvedores',
    'home.why.dna1.desc': 'Sem gerentes de contas. Você fala diretamente com os engenheiros que constroem seu produto.',
    'home.why.dna2.title': 'Engenharia Focada em Negócios',
    'home.why.dna2.desc': 'Código é um meio para impulsionar métricas e receita. Projetamos com foco em escalabilidade.',
    'home.why.dna3.title': 'Transparência Meticulosa',
    'home.why.dna3.desc': 'Acesso em tempo real a repositórios, pipelines de teste e sprints. Alinhamento diário.',
    'home.why.dna4.title': 'Iteração Rápida',
    'home.why.dna4.desc': 'Ciclos de sprint semanais com entregáveis claros, feedback contínuo e deploys em produção.',

    'home.work.eyebrow': 'Projetos Selecionados',
    'home.work.title': 'Trabalhos dos quais nos orgulhamos',
    'home.work.cta': 'Ver todos os projetos',

    'home.faq.eyebrow': 'FAQ',
    'home.faq.title': 'Perguntas\nFrequentes',

    'home.cta.title': 'Vamos construir juntos.',
    'home.cta.btn': 'Agendar uma chamada de descoberta',

    // About
    'about.hero.eyebrow': 'Sobre a Codnexa',
    'about.hero.title': 'Um estúdio que entrega\num trabalho excepcional.',
    'about.intro.p1': 'A Codnexa é um estúdio digital boutique fundado na crença de que software de excelência une estratégia, design e tecnologia, sem atalhos.',
    'about.intro.p2': 'Somos um time sênior e compacto. Sem programadores juniores aprendendo com seu projeto. Comunicação direta e entregas ágeis.',
    'about.intro.p3': 'Fundado em 2016, temos apoiado startups e empresas em fintech, saúde digital, comércio eletrônico e SaaS.',
    'about.stats.projects': 'Projetos',
    'about.stats.years': 'Anos',
    'about.stats.continents': 'Continentes',
    'about.principles.eyebrow': 'Nossos Princípios',
    'about.principles.title': 'Os valores que guiam nosso trabalho',
    'about.principles.1.title': 'Transparência Total',
    'about.principles.1.desc': 'Sem surpresas. Acesso total em tempo real aos repositórios de código, sprints e decisões do projeto.',
    'about.principles.2.title': 'Qualidade Inabalável',
    'about.principles.2.desc': 'Código limpo, seguro e testado com sistemas de design escaláveis livres de débito técnico.',
    'about.principles.3.title': 'Foco no Usuário',
    'about.principles.3.desc': 'Interfaces devem ser intuitivas, elegantes e acessíveis. Desenhamos com validação de dados.',
    'about.principles.4.title': 'Valor de Negócio',
    'about.principles.4.desc': 'Medimos nosso código pelos resultados gerados: taxa de conversão, velocidade e resiliência.',
    'about.team.eyebrow': 'O Time',
    'about.team.title': 'Construído por quem\nse importa com código',
    'about.team.founder1.role': 'Co-Fundador & Tech Lead',
    'about.team.founder1.bio': 'Arquiteto full-stack com 8+ anos desenvolvendo sistemas complexos em fintech, nuvem e SaaS.',
    'about.team.founder2.role': 'Co-Fundadora & Diretora de Design',
    'about.team.founder2.bio': 'Product designer especialista em fluxos de informação e interfaces focadas em conversões.',
    'about.cta.title': 'Construa algo extraordinário.',
    'about.cta.desc': 'Tem uma ideia em mente? Adoraríamos ouvir sobre o seu projeto.',
    'about.cta.btn1': 'Iniciar um Projeto',
    'about.cta.btn2': 'Ver nossos projetos',

    // Services
    'services.hero.eyebrow': 'Nossos Serviços',
    'services.hero.title': 'O que nós\noferecemos.',
    'services.hero.desc': 'Estratégia, design e código. De identidades visuais a arquiteturas em nuvem complexas: entregamos soluções completas.',
    'services.cta.title': 'Pronto para começar seu projeto?',
    'services.cta.desc': 'Agende um bate-papo gratuito para definirmos seu projeto juntos.',
    'services.cta.btn': 'Agendar chamada exploratória',
    'services.process.eyebrow': 'Nosso Processo',
    'services.process.title': 'Como\ntrabalhamos',
    'services.process.desc': 'Seguimos uma metodologia estruturada visando velocidade, comunicação aberta e qualidade máxima.',

    // Portfolio
    'portfolio.hero.eyebrow': 'Projetos',
    'portfolio.hero.title': 'Estudos de caso e\nplataformas digitais.',
    'portfolio.hero.desc': 'Construímos soluções rápidas, robustas e integradas para líderes de mercado.',
    'portfolio.testimonials.eyebrow': 'Depoimentos',
    'portfolio.testimonials.title': 'O que nossos\nparceiros dizem',
    'portfolio.testimonials.desc': 'Medimos o sucesso pelos resultados comerciais reais que destravamos para os clientes.',

    // Contact
    'contact.hero.eyebrow': 'Contato',
    'contact.hero.title': 'Escreva para\no estúdio',
    'contact.hero.desc': 'Pronto para levar seu produto digital ao topo? Preencha o brief ou reserve um horário direto.',
    'contact.info.office': 'Escritório',
    'contact.info.hours': 'Atendimento',
    'contact.info.hours.val': 'Seg – Sex, 9h – 18h',
    'contact.tabs.brief': 'Enviar Briefing',
    'contact.tabs.call': 'Agendar Chamada',
    'contact.form.name': 'Seu Nome',
    'contact.form.email': 'Seu Email',
    'contact.form.focus': 'Foco do Projeto',
    'contact.form.focus.placeholder': 'Selecione uma opção...',
    'contact.form.budget': 'Orçamento Estimado',
    'contact.form.message': 'Detalhes do Projeto',
    'contact.form.message.placeholder': 'Conte-nos sobre suas metas, escopo, prazos desejados...',
    'contact.form.submit': 'Enviar Pedido',
    'contact.form.success.title': 'Obrigado!',
    'contact.form.success.desc': 'Recebemos as suas informações. Nosso time responderá em até 24 horas úteis.',
    'contact.form.success.btn': 'Enviar outra mensagem',
    'contact.book.timezone': 'Seu Fuso Horário',
    'contact.book.select': 'Selecione Dia e Hora',
    'contact.book.submit': 'Confirmar Agendamento',
    'contact.book.success.title': 'Chamada Agendada!',
    'contact.book.success.desc': 'A sua chamada de descoberta está agendada para',
  },
  RU: {
    // Nav
    'nav.services': 'Услуги',
    'nav.work': 'Портфолио',
    'nav.about': 'О студии',
    'nav.contact': 'Контакты',
    'nav.cta': 'Начать проект',
    'nav.theme': 'Сменить тему',
    'nav.lang': 'Выбрать язык',

    // Footer
    'footer.cta.eyebrow': 'Начать проект',
    'footer.cta.title': 'Готовы создать\nчто-то выдающееся?',
    'footer.cta.btn': 'Связаться с нами',
    'footer.desc': 'Студия стратегии, дизайна и разработки. Мы создаем то, что помогает амбициозным компаниям лидировать.',
    'footer.studio': 'Студия',
    'footer.legal': 'Юридическая инфо',
    'footer.contact': 'Контакты',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.terms': 'Условия использования',
    'footer.cookies': 'Файлы cookies',
    'footer.rights': 'Все права защищены.',

    // Home
    'home.hero.eyebrow': 'Студия стратегии, дизайна и разработки',
    'home.hero.title': 'Креативная студия\nдля вашей',
    'home.hero.desc': 'Стратегия, дизайн и разработка. От айдентики бренда до сложных платформ, мы создаем то, что нужно бизнесу для лидерства.',
    'home.hero.cta.work': 'Наши проекты',
    'home.hero.cta.project': 'Начать проект',
    'home.meta.scroll': 'Прокрутите для изучения',
    'home.hero.typewriter': 'Стратегия,Разработка,Дизайн,Инновации,Совершенство',

    'home.services.eyebrow': 'Наши услуги',
    'home.services.title': 'Выбранные области экспертизы',
    'home.services.cta': 'Все услуги студии',

    'home.why.eyebrow': 'Наше ДНК',
    'home.why.title': 'Почему лидеры выбирают Codnexa',
    'home.why.dna1.title': 'Прямой контакт с разработчиком',
    'home.why.dna1.desc': 'Никаких аккаунт-менеджеров. Вы общаетесь напрямую с инженерами, создающими ваш продукт.',
    'home.why.dna2.title': 'Инженерия для бизнеса',
    'home.why.dna2.desc': 'Код это инструмент роста бизнес-показателей. Мы проектируем системы с расчетом на масштабирование.',
    'home.why.dna3.title': 'Абсолютная прозрачность',
    'home.why.dna3.desc': 'Полный доступ к репозиториям, тестовым средам и спринтам. Ежедневные отчеты.',
    'home.why.dna4.title': 'Быстрые итерации',
    'home.why.dna4.desc': 'Еженедельные спринты с понятными целями, регулярной обратной связью и выкатом в прод.',

    'home.work.eyebrow': 'Кейсы',
    'home.work.title': 'Проекты, которыми мы гордимся',
    'home.work.cta': 'Посмотреть все кейсы',

    'home.faq.eyebrow': 'Вопросы и ответы',
    'home.faq.title': 'Частые\nВопросы',

    'home.cta.title': 'Давайте создадим это вместе.',
    'home.cta.btn': 'Заказать звонок-обсуждение',

    // About
    'about.hero.eyebrow': 'О студии',
    'about.hero.title': 'Студия, которая создает\nисключительные продукты.',
    'about.intro.p1': 'Codnexa это бутиковая цифровая студия. Мы верим, что отличный продукт находится на стыке бизнес-стратегии, дизайна и технологий.',
    'about.intro.p2': 'Мы компактная команда сеньор-специалистов. Никаких джунов, обучающихся на вашем проекте. Только эксперты с фокусом на результат.',
    'about.intro.p3': 'Основанная в 2016 году, наша студия помогла запустить и масштабировать десятки стартапов и технологических платформ.',
    'about.stats.projects': 'Проектов',
    'about.stats.years': 'Лет',
    'about.stats.continents': 'Континентов',
    'about.principles.eyebrow': 'Наши Принципы',
    'about.principles.title': 'Ценности, которыми мы руководствуемся',
    'about.principles.1.title': 'Полная прозрачность',
    'about.principles.1.desc': 'Никаких неожиданных сдвигов сроков. Полный доступ к коду в реальном времени, таск-трекеру и логам решений.',
    'about.principles.2.title': 'Бескомпромиссное качество',
    'about.principles.2.desc': 'Мы пишем чистый, готовый к продакшену код с автотестами и масштабируемой архитектурой без долгов.',
    'about.principles.3.title': 'Дизайн для людей',
    'about.principles.3.desc': 'Интерфейсы должны быть красивыми, быстрыми и логичными. Каждая кнопка должна решать задачу.',
    'about.principles.4.title': 'Ориентированность на метрики',
    'about.principles.4.desc': 'Мы оцениваем качество кода по успехам вашего бизнеса: конверсиям, скорости загрузки и стабильности.',
    'about.team.eyebrow': 'Команда',
    'about.team.title': 'Создано людьми,\nкоторые любят свое дело',
    'about.team.founder1.role': 'Сооснователь & Технический директор',
    'about.team.founder1.bio': 'Full-stack архитектор с 8+ годами опыта запуска продуктов в сферах финтех, SaaS и облачных платформ.',
    'about.team.founder2.role': 'Сооснователь & Арт-директор',
    'about.team.founder2.bio': 'Продуктовый дизайнер, специализирующийся на сложных пользовательских сценариях и конверсионном дизайне интерфейсов.',
    'about.cta.title': 'Давайте создадим что-то выдающееся.',
    'about.cta.desc': 'У вас есть идея или проект? Мы будем рады обсудить детали.',
    'about.cta.btn1': 'Начать проект',
    'about.cta.btn2': 'Наши кейсы',

    // Services
    'services.hero.eyebrow': 'Наши Услуги',
    'services.hero.title': 'Что мы\nделаем.',
    'services.hero.desc': 'Стратегия, дизайн и разработка. От проработки концепции бренда до построения сложных облачных архитектур.',
    'services.cta.title': 'Готовы обсудить ваш проект?',
    'services.cta.desc': 'Запишитесь на бесплатную консультацию, и мы вместе проработаем архитектуру решения.',
    'services.cta.btn': 'Заказать звонок-обсуждение',
    'services.process.eyebrow': 'Процесс работы',
    'services.process.title': 'Как мы\nработаем',
    'services.process.desc': 'Каждое наше партнерство строится на четко структурированной методологии для быстрой и качественной сдачи задач.',

    // Portfolio
    'portfolio.hero.eyebrow': 'Кейсы',
    'portfolio.hero.title': 'Истории успеха и\nцифровые продукты.',
    'portfolio.hero.desc': 'Мы помогаем технологическим лидерам создавать быстрые, удобные и конверсионные веб-платформы.',
    'portfolio.testimonials.eyebrow': 'Отзывы клиентов',
    'portfolio.testimonials.title': 'Что о нас говорят\nнаши партнеры',
    'portfolio.testimonials.desc': 'Мы измеряем свою эффективность ценностью, которую наш код приносит вашему бизнесу.',

    // Contact
    'contact.hero.eyebrow': 'Контакты',
    'contact.hero.title': 'Связаться со\nстудией',
    'contact.hero.desc': 'Готовы запустить продукт на новый уровень? Заполните бриф или забронируйте удобное время для звонка.',
    'contact.info.office': 'Офис',
    'contact.info.hours': 'Время работы',
    'contact.info.hours.val': 'Пн – Пт, с 9:00 до 18:00',
    'contact.tabs.brief': 'Заполнить Бриф',
    'contact.tabs.call': 'Выбрать Время',
    'contact.form.name': 'Ваше имя',
    'contact.form.email': 'Email-адрес',
    'contact.form.focus': 'Направление проекта',
    'contact.form.focus.placeholder': 'Выберите категорию...',
    'contact.form.budget': 'Примерный бюджет',
    'contact.form.message': 'О проекте',
    'contact.form.message.placeholder': 'Расскажите о ваших целях, требованиях, сроках...',
    'contact.form.submit': 'Отправить запрос',
    'contact.form.success.title': 'Спасибо!',
    'contact.form.success.desc': 'Ваш бриф успешно получен. Мы изучим его и свяжемся с вами в течение 24 часов.',
    'contact.form.success.btn': 'Отправить еще один запрос',
    'contact.book.timezone': 'Ваш часовой пояс',
    'contact.book.select': 'Выберите дату и время',
    'contact.book.submit': 'Подтвердить звонок',
    'contact.book.success.title': 'Звонок забронирован!',
    'contact.book.success.desc': 'Мы свяжемся с вами для детального обсуждения',
  },
  HI: {
    // Nav
    'nav.services': 'सेवाएं',
    'nav.work': 'काम',
    'nav.about': 'परिचय',
    'nav.contact': 'संपर्क',
    'nav.cta': 'परियोजना शुरू करें',
    'nav.theme': 'थीम बदलें',
    'nav.lang': 'भाषा चुनें',

    // Footer
    'footer.cta.eyebrow': 'परियोजना शुरू करें',
    'footer.cta.title': 'कुछ बेहतरीन बनाने के लिए\nतैयार हैं?',
    'footer.cta.btn': 'संपर्क में रहें',
    'footer.desc': 'रणनीति, डिज़ाइन और विकास स्टूडियो। हम वही बनाते हैं जिसकी महत्वाकांक्षी कंपनियों को नेतृत्व करने के लिए आवश्यकता होती है।',
    'footer.studio': 'स्टूडियो',
    'footer.legal': 'कानूनी',
    'footer.contact': 'संपर्क',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'उपयोग की शर्तें',
    'footer.cookies': 'कुकीज़',
    'footer.rights': 'सर्वाधिकार सुरक्षित।',

    // Home
    'home.hero.eyebrow': 'रणनीति, डिज़ाइन और विकास स्टूडियो',
    'home.hero.title': 'रचनात्मक स्टूडियो\nबनाया गया है',
    'home.hero.desc': 'रणनीति, डिज़ाइन और विकास। ब्रांड पहचान से लेकर पूर्ण-स्तरीय प्लेटफ़ॉर्म तक, हम वह बनाते हैं जिसकी कंपनियों को नेतृत्व करने की आवश्यकता होती है।',
    'home.hero.cta.work': 'हमारा काम देखें',
    'home.hero.cta.project': 'परियोजना शुरू करें',
    'home.meta.scroll': 'खोजने के लिए स्क्रॉल करें',
    'home.hero.typewriter': 'रणनीति,विकास,डिज़ाइन,नवाचार,उत्कृष्टता',

    'home.services.eyebrow': 'हम क्या करते हैं',
    'home.services.title': 'विशेषज्ञता के चयनित क्षेत्र',
    'home.services.cta': 'सभी सेवाओं का पता लगाएं',

    'home.why.eyebrow': 'हमारा डीएनए',
    'home.why.title': 'अग्रणी ब्रांड कोडनेक्सा को क्यों चुनते हैं',
    'home.why.dna1.title': 'सीधा डेवलपर लूप',
    'home.why.dna1.desc': 'कोई खाता प्रबंधक नहीं। आप सीधे अपने उत्पाद का निर्माण करने वाले इंजीनियरों से बात करते हैं।',
    'home.why.dna2.title': 'व्यापार-उन्मुख इंजीनियरिंग',
    'home.why.dna2.desc': 'कोड मेट्रिक्स और राजस्व बढ़ाने का एक तंत्र है। हम विकास के साथ-साथ विस्तार करने के लिए आर्किटेक्चर बनाते हैं।',
    'home.why.dna3.title': 'सूक्ष्म पारदर्शिता',
    'home.why.dna3.desc': 'रिपॉजिटरी, स्टेजिंग पाइपलाइनों और स्प्रिंट पर पूर्ण दृश्यता। दिन-प्रतिदिन की जवाबदेही।',
    'home.why.dna4.title': 'तीव्र पुनरावृत्ति',
    'home.why.dna4.desc': 'स्पष्ट डिलिवरेबल्स, फीडबैक लूप और उत्पादन परिनियोजन के साथ साप्ताहिक स्प्रिंट चक्र।',

    'home.work.eyebrow': 'चयनित काम',
    'home.work.title': 'वह काम जिस पर हमें गर्व है',
    'home.work.cta': 'सभी काम देखें',

    'home.faq.eyebrow': 'अक्सर पूछे जाने वाले प्रश्न',
    'home.faq.title': 'सामान्य\nप्रश्न',

    'home.cta.title': 'आइए इसे मिलकर बनाएं।',
    'home.cta.btn': 'एक खोज कॉल बुक करें',

    // About
    'about.hero.eyebrow': 'कोडनेक्सा के बारे में',
    'about.hero.title': 'एक स्टूडियो जो वितरित करता है\nअसाधारण काम।',
    'about.intro.p1': 'कोडनेक्सा एक बुटीक डिजिटल स्टूडियो है जिसकी स्थापना इस विश्वास पर की गई है कि बेहतरीन सॉफ्टवेयर रणनीति, डिज़ाइन और इंजीनियरिंग का प्रतिच्छेदन है, उनके बीच का समझौता नहीं।',
    'about.intro.p2': 'हम एक छोटी, वरिष्ठ टीम हैं। कोई जूनियर डेवलपर आपकी परियोजना पर सीख नहीं रहा है। बफ़र के रूप में कोई खाता प्रबंधक नहीं। बस अनुभवी इंजीनियर और डिज़ाइनर जो अपने द्वारा बनाए जाने वाले उत्पादों की गहराई से परवाह करते हैं।',
    'about.intro.p3': '2016 में स्थापित, हमने फ़िनटेक, हेल्थटेक, ई-कॉमर्स और SaaS में स्टार्टअप्स, स्केलअप्स और स्थापित उद्यमों के साथ भागीदारी की है, हमेशा शिल्प के प्रति समान प्रतिबद्धता के साथ।',
    'about.stats.projects': 'परियोजनाएं',
    'about.stats.years': 'वर्ष',
    'about.stats.continents': 'महाद्वीप',
    'about.principles.eyebrow': 'हमारे सिद्धांत',
    'about.principles.title': 'वे मूल्य जो हर निर्णय का मार्गदर्शन करते हैं',
    'about.principles.1.title': 'पूर्ण पारदर्शिता',
    'about.principles.1.desc': 'कोई छिपी हुई समयसीमा या आश्चर्य नहीं। कोड रिपॉजिटरी, स्प्रिंट प्रगति और निर्णय लेने वाले लॉग तक वास्तविक समय की पहुंच।',
    'about.principles.2.title': 'बिना समझौते के गुणवत्ता',
    'about.principles.2.desc': 'हम बिना किसी तकनीकी ऋण के परीक्षण कवरेज और डिज़ाइन प्रणालियों के साथ स्वच्छ, उत्पादन के लिए तैयार कोड लिखते हैं।',
    'about.principles.3.title': 'उपयोगकर्ता-केंद्रित डिज़ाइन',
    'about.principles.3.desc': 'इंटरफेस सुंदर, सुलभ और सहज होने चाहिए। हम उद्देश्य और सत्यापन के साथ डिज़ाइन करते हैं।',
    'about.principles.4.title': 'मेट्रिक-संचालित इंजीनियरिंग',
    'about.principles.4.desc': 'हम अपने कोड को व्यावसायिक परिणामों से मापते हैं: रूपांतरण दरें, पृष्ठ गति और बुनियादी ढांचा लचीलापन।',
    'about.team.eyebrow': 'टीम',
    'about.team.title': 'परवाह करने वाले लोगों\nद्वारा निर्मित',
    'about.team.founder1.role': 'सह-संस्थापक और तकनीकी प्रमुख',
    'about.team.founder1.bio': 'फ़िनटेक, SaaS और उद्यम में उत्पादन प्रणालियों को वितरित करने वाले 8+ वर्षों के अनुभव के साथ फुल-स्टैक आर्किटेक्ट।',
    'about.team.founder2.role': 'सह-संस्थापक और डिज़ाइन निदेशक',
    'about.team.founder2.bio': 'जटिल सूचना डिज़ाइन और रूपांतरण-केंद्रित UI में विशेषज्ञता रखने वाले उत्पाद डिज़ाइनर।',
    'about.cta.title': 'आइए कुछ असाधारण बनाएं।',
    'about.cta.desc': 'क्या आपके पास कोई परियोजना या साझेदारी है? हम आपसे सुनना पसंद करेंगे।',
    'about.cta.btn1': 'परियोजना शुरू करें',
    'about.cta.btn2': 'हमारा काम देखें',

    // Services
    'services.hero.eyebrow': 'हमारी सेवाएं',
    'services.hero.title': 'हम क्या\nपेश करते हैं।',
    'services.hero.desc': 'रणनीति, डिज़ाइन और विकास। ब्रांड पहचान से लेकर पूर्ण-स्तरीय प्लेटफ़ॉर्म और सॉफ़्टवेयर तक, हम वह बनाते हैं जिसकी कंपनियों को नेतृत्व करने की आवश्यकता होती है।',
    'services.cta.title': 'अपनी परियोजना शुरू करने के लिए तैयार हैं?',
    'services.cta.desc': 'एक मुफ्त खोज कॉल बुक करें और हम मिलकर आपके दृष्टिकोण का दायरा तय करेंगे।',
    'services.cta.btn': 'एक खोज कॉल बुक करें',
    'services.process.eyebrow': 'हमारी प्रक्रिया',
    'services.process.title': 'हम कैसे\nकाम करते हैं',
    'services.process.desc': 'हर जुड़ाव स्पष्टता, गति और गुणवत्ता के लिए डिज़ाइन किए गए एक संरचित वर्कफ़्लो का अनुसरण करता है।',

    // Portfolio
    'portfolio.hero.eyebrow': 'चयनित काम',
    'portfolio.hero.title': 'केस स्टडीज और\nडिजिटल प्लेटफॉर्म।',
    'portfolio.hero.desc': 'हम स्वच्छ, प्रदर्शन करने वाले और उच्च-परिवर्तित प्रणालियों को इंजीनियर करने के लिए महत्वाकांक्षी स्टार्टअप और दुनिया के अग्रणी ब्रांडों के साथ सहयोग करते हैं।',
    'portfolio.testimonials.eyebrow': 'अनुमोदन',
    'portfolio.testimonials.title': 'ग्राहक हमारे बारे\nमें क्या कहते हैं',
    'portfolio.testimonials.desc': 'हम सफलता को अपने ग्राहकों के लिए मिलने वाले परिणामों से मापते हैं, न कि केवल कोड वितरित करके।',

    // Contact
    'contact.hero.eyebrow': 'संपर्क करें',
    'contact.hero.title': 'संपर्क में\nरहें',
    'contact.hero.desc': 'अपने डिजिटल अनुभव को बदलने के लिए तैयार हैं? संक्षिप्त विवरण भरें या सीधे परामर्श के लिए एक स्लॉट चुनें।',
    'contact.info.office': 'कार्यालय',
    'contact.info.hours': 'घंटे',
    'contact.info.hours.val': 'सोम – शुक्र, सुबह 9 – शाम 6 बजे',
    'contact.tabs.brief': 'परियोजना संक्षिप्त',
    'contact.tabs.call': 'कॉल बुक करें',
    'contact.form.name': 'आपका नाम',
    'contact.form.email': 'आपका ईमेल',
    'contact.form.focus': 'परियोजना फोकस',
    'contact.form.focus.placeholder': 'एक श्रेणी चुनें...',
    'contact.form.budget': 'अनुमानित बजट',
    'contact.form.message': 'परियोजना विवरण',
    'contact.form.message.placeholder': 'हमें अपनी परियोजना, लक्ष्यों, समयसीमा के बारे में बताएं...',
    'contact.form.submit': 'पूछताछ भेजें',
    'contact.form.success.title': 'धन्यवाद',
    'contact.form.success.desc': 'आपकी परियोजना का संक्षिप्त विवरण प्राप्त हो गया है। हमारी टीम इसकी समीक्षा करेगी और 24 घंटे के भीतर आपसे संपर्क करेगी।',
    'contact.form.success.btn': 'दूसरा संदेश भेजें',
    'contact.book.timezone': 'आपका समय क्षेत्र',
    'contact.book.select': 'दिनांक और समय चुनें',
    'contact.book.submit': 'कॉल बुकिंग की पुष्टि करें',
    'contact.book.success.title': 'बुकिंग की पुष्टि हो गई!',
    'contact.book.success.desc': 'आपकी खोज कॉल निर्धारित है',
  },
  ZH: {
    // Nav
    'nav.services': '服务项目',
    'nav.work': '精品案例',
    'nav.about': '关于我们',
    'nav.contact': '联系我们',
    'nav.cta': '开启项目',
    'nav.theme': '切换主题',
    'nav.lang': '选择语言',

    // Footer
    'footer.cta.eyebrow': '开启项目',
    'footer.cta.title': '准备好构建\n伟大的产品了吗？',
    'footer.cta.btn': '取得联系',
    'footer.desc': '策略、设计与开发工作室。我们构建雄心勃勃的企业引领行业所需的一切。',
    'footer.studio': '工作室',
    'footer.legal': '法律信息',
    'footer.contact': '联系方式',
    'footer.privacy': '隐私政策',
    'footer.terms': '使用条款',
    'footer.cookies': 'Cookies 设置',
    'footer.rights': '版权所有。',

    // Home
    'home.hero.eyebrow': '策略、设计与开发工作室',
    'home.hero.title': '创意工作室\n专为',
    'home.hero.desc': '策略、设计与开发。从品牌识别到全尺寸平台，我们构建企业引领行业所需的一切。',
    'home.hero.cta.work': '浏览案例',
    'home.hero.cta.project': '开启项目',
    'home.meta.scroll': '向下滚动探索',
    'home.hero.typewriter': '战略,开发,设计,创新,卓越',

    'home.services.eyebrow': '业务范围',
    'home.services.title': '精选核心技术领域',
    'home.services.cta': '探索全部服务',

    'home.why.eyebrow': '企业基因',
    'home.why.title': '为什么领先品牌选择 Codnexa',
    'home.why.dna1.title': '开发者直接沟通',
    'home.why.dna1.desc': '没有客户经理。您直接与构建您产品的工程师对话。',
    'home.why.dna2.title': '业务导向工程',
    'home.why.dna2.desc': '代码是驱动数据和营收的机制。我们的架构设计与您的业务一同增长。',
    'home.why.dna3.title': '极度透明透明',
    'home.why.dna3.desc': '对代码仓库、测试环境和开发进度拥有完整视野。每日成果公开。',
    'home.why.dna4.title': '快速迭代',
    'home.why.dna4.desc': '每周为一个开发周期，包含明确交付物、反馈闭环和线上部署。',

    'home.work.eyebrow': '精品案例',
    'home.work.title': '让我们引以为傲的作品',
    'home.work.cta': '浏览所有案例',

    'home.faq.eyebrow': '常见问题',
    'home.faq.title': '常见\n问题',

    'home.cta.title': '让我们携手共建。',
    'home.cta.btn': '预约项目咨询电话',

    // About
    'about.hero.eyebrow': '关于 Codnexa',
    'about.hero.title': '一家交付\n杰出作品的工作室。',
    'about.intro.p1': 'Codnexa 是一家精品数字工作室，创立的初衷是坚信优秀的软件是策略、设计与工程的完美交汇，而不是它们之间的妥协。',
    'about.intro.p2': '我们是一支全资深小型团队。没有实习生在您的项目上练手。没有繁琐的中间汇报人。只有热爱交付高质量产品的资深专家。',
    'about.intro.p3': '自2016年成立以来，我们与金融科技、数字健康、电子商务和 SaaS 领域的初创公司和大型企业建立了合作，始终保持对工艺的追求。',
    'about.stats.projects': '项目',
    'about.stats.years': '年资历',
    'about.stats.continents': '覆盖大洲',
    'about.principles.eyebrow': '我们的原则',
    'about.principles.title': '指引我们做出每个决定的价值观',
    'about.principles.1.title': '绝对透明',
    'about.principles.1.desc': '没有隐藏的开发时间线或意外情况。实时访问代码仓库、开发日志和决策记录。',
    'about.principles.2.title': '不妥协的质量',
    'about.principles.2.desc': '我们编写整洁、生产就绪的代码，包含自动化测试和易扩展的组件系统，拒绝技术债务。',
    'about.principles.3.title': '以用户为中心',
    'about.principles.3.desc': '界面必须优美、易用且符合直觉。我们的每一次设计都有其目的，并经过验证。',
    'about.principles.4.title': '数据结果驱动',
    'about.principles.4.desc': '我们通过真实的业务结果来衡量代码好坏：转化率、首屏速度和架构稳定性。',
    'about.team.eyebrow': '团队介绍',
    'about.team.title': '由追求极致的\n专业人士构建',
    'about.team.founder1.role': '联合创始人 & 技术负责人',
    'about.team.founder1.bio': '资深 Full-stack 架构师，拥有 8 年以上在金融科技和 SaaS 领域构建大型系统的经验。先前曾就职于一线咨询公司。',
    'about.team.founder2.role': '联合创始人 & 设计总监',
    'about.team.founder2.bio': '专注复杂信息层级规划及高转化界面视觉的数字产品设计师。无障碍访问的倡导者。',
    'about.cta.title': '让我们一起做点出色的事情。',
    'about.cta.desc': '有项目想法或商务合作？我们很乐意倾听。',
    'about.cta.btn1': '开启项目',
    'about.cta.btn2': '浏览案例',

    // Services
    'services.hero.eyebrow': '我们的服务',
    'services.hero.title': '我们\n提供什么。',
    'services.hero.desc': '策略、设计和开发。从品牌视觉体系构建到弹性云端架构设计，我们开发企业引领行业所需的一切。',
    'services.cta.title': '准备好开启项目了吗？',
    'services.cta.desc': '预约一个免费的开发咨询电话，共同细化您的产品愿景。',
    'services.cta.btn': '预约项目咨询电话',
    'services.process.eyebrow': '开发流程',
    'services.process.title': '我们如何\n开展工作',
    'services.process.desc': '每一个项目都遵循结构化开发流程，旨在保障项目交付的清晰度、速度与最高质量。',

    // Portfolio
    'portfolio.hero.eyebrow': '精品案例',
    'portfolio.hero.title': '商业案例 &\n数字平台。',
    'portfolio.hero.desc': '我们与雄心勃勃的初创公司和全球领先品牌合作，设计和构建整洁、高效、高转化的软件系统。',
    'portfolio.testimonials.eyebrow': '客户证言',
    'portfolio.testimonials.title': '合作伙伴的\n真实评价',
    'portfolio.testimonials.desc': '我们以我们为客户业务带来的真实提升来衡量项目的成功，而不仅仅是按期交付代码。',

    // Contact
    'contact.hero.eyebrow': '联系我们',
    'contact.hero.title': '与我们\n取得联系',
    'contact.hero.desc': '准备好升级您的数字化体验了吗？填写以下需求，或直接预约我们的咨询会议。',
    'contact.info.office': '办公室',
    'contact.info.hours': '工作时间',
    'contact.info.hours.val': '周一至周五，早上 9 点 – 下午 6 点',
    'contact.tabs.brief': '项目简报',
    'contact.tabs.call': '预约会议',
    'contact.form.name': '您的姓名',
    'contact.form.email': '您的电子邮箱',
    'contact.form.focus': '项目类型',
    'contact.form.focus.placeholder': '选择一个类别...',
    'contact.form.budget': '预估预算',
    'contact.form.message': '项目细节',
    'contact.form.message.placeholder': '告诉我们关于您的项目、目标、预期时间线...',
    'contact.form.submit': '提交需求',
    'contact.form.success.title': '非常感谢！',
    'contact.form.success.desc': '我们已收到您的项目简报。我们的技术专家会进行评估，并在 24 小时内与您回复。',
    'contact.form.success.btn': '提交另一个需求',
    'contact.book.timezone': '您所在的时区',
    'contact.book.select': '选择日期与时间',
    'contact.book.submit': '确认预约会议',
    'contact.book.success.title': '会议预约成功！',
    'contact.book.success.desc': '您的咨询会议已安排在',
  },
  JA: {
    // Nav
    'nav.services': 'サービス',
    'nav.work': '実績',
    'nav.about': 'スタジオ',
    'nav.contact': 'お問い合わせ',
    'nav.cta': 'プロジェクト相談',
    'nav.theme': 'テーマ切り替え',
    'nav.lang': '言語選択',

    // Footer
    'footer.cta.eyebrow': 'プロジェクトを開始する',
    'footer.cta.title': '素晴らしい製品を\n一緒に作りませんか？',
    'footer.cta.btn': 'お問い合わせ',
    'footer.desc': '戦略、デザイン、そして開発スタジオ。私たちは意欲的な企業が業界をリードするために必要な製品を構築します。',
    'footer.studio': 'スタジオ',
    'footer.legal': '法的情報',
    'footer.contact': 'お問い合わせ',
    'footer.privacy': 'プライバシーポリシー',
    'footer.terms': '利用規約',
    'footer.cookies': 'クッキー設定',
    'footer.rights': 'All rights reserved.',

    // Home
    'home.hero.eyebrow': '戦略・デザイン・開発スタジオ',
    'home.hero.title': 'クリエイティブ・スタジオ\n目的は',
    'home.hero.desc': '戦略、デザイン、そして開発。ブランドアイデンティティから大規模なプラットフォームまで、企業が業界をリードするために必要なデジタル製品を開発します。',
    'home.hero.cta.work': '実績を見る',
    'home.hero.cta.project': 'プロジェクト相談',
    'home.meta.scroll': 'スクロールして探索',
    'home.hero.typewriter': '戦略,開発,デザイン,革新,卓越',

    'home.services.eyebrow': '事業内容',
    'home.services.title': '厳選されたコア専門領域',
    'home.services.cta': 'すべてのサービスを見る',

    'home.why.eyebrow': '企業アイデンティティ',
    'home.why.title': '一流ブランドがCodnexaを選ぶ理由',
    'home.why.dna1.title': '開発者との直接ダイアログ',
    'home.why.dna1.desc': 'アカウントマネージャーはいません。製品を構築するエンジニアと直接コミュニケーションをとります。',
    'home.why.dna2.title': 'ビジネス志向のエンジニアリング',
    'home.why.dna2.desc': 'コードはビジネス指標と売上を向上させるための手段です。将来の成長を見据えて設計します。',
    'home.why.dna3.title': '徹底的な透明性',
    'home.why.dna3.desc': 'リポジトリ、テスト環境、スプリントへの完全なアクセスを提供。毎日の進捗を明確に公開します。',
    'home.why.dna4.title': '迅速なイテレーション',
    'home.why.dna4.desc': '明確な成果物、フィードバックループ、本番デプロイを含む、毎週のスプリント開発サイクル。',

    'home.work.eyebrow': '実績紹介',
    'home.work.title': '私たちが誇りとする実績',
    'home.work.cta': 'すべての実績を見る',

    'home.faq.eyebrow': 'よくある質問',
    'home.faq.title': 'よくある\nご質問',

    'home.cta.title': '一緒に作り上げましょう。',
    'home.cta.btn': '無料相談を予約する',

    // About
    'about.hero.eyebrow': 'Codnexaについて',
    'about.hero.title': '卓越したクオリティを\n追求するスタジオ。',
    'about.intro.p1': 'Codnexaは、優れたソフトウェアとは戦略、デザイン、技術の交差点であり、どれも妥協すべきではないという信念のもとに設立されたブティック・デジタルスタジオです。',
    'about.intro.p2': '私たちは全員がシニアレベルの少数精鋭チームです。あなたのプロジェクトを練習台にするようなジュニア開発者は一人もいません。開発者と直接会話できます。',
    'about.intro.p3': '2016年の設立以来、フィンテック、医療テック、Eコマース、SaaSの分野で、スタートアップから大手企業まで幅広くサポートしてきました。',
    'about.stats.projects': 'プロジェクト',
    'about.stats.years': '年以上の実績',
    'about.stats.continents': 'グローバル展開',
    'about.principles.eyebrow': '私たちの行動指針',
    'about.principles.title': 'すべての決定の土台となる価値観',
    'about.principles.1.title': '絶対的な透明性',
    'about.principles.1.desc': '不透明なスケジュールはありません。リポジトリ、開発スプリント、意思決定ログへの完全なリアルタイムアクセス。',
    'about.principles.2.title': '妥協のない品質',
    'about.principles.2.desc': 'テスト駆動開発と技術負債のない拡張性の高いデザインシステムを用いて、クリーンで堅牢なコードを書きます。',
    'about.principles.3.title': 'ユーザー中心設計',
    'about.principles.3.desc': 'インターフェースは美しく、使いやすく、直感的でなければなりません。検証に基づいた明確なデザイン。',
    'about.principles.4.title': '指標重視のエンジニアリング',
    'about.principles.4.desc': '私たちはコンバージョン率、読み込み速度、インフラの堅牢性など、ビジネス成果でコードの質を評価します。',
    'about.team.eyebrow': 'メンバー',
    'about.team.title': '細部へのこだわりを\n持つ専門家チーム',
    'about.team.founder1.role': '共同創業者 兼 技術責任者',
    'about.team.founder1.bio': 'フィンテックやSaaS分野で8年以上の製品開発とインフラ構築の実績を持つフルスタック・アーキテクト。',
    'about.team.founder2.role': '共同創業者 兼 デザインディレクター',
    'about.team.founder2.bio': '複雑な情報設計とコンバージョン率の最大化を得意とするプロダクトデザイナー。',
    'about.cta.title': '卓越したデジタル製品を作りましょう。',
    'about.cta.desc': '新規プロジェクトやアライアンスのご相談はお気軽にご連絡ください。',
    'about.cta.btn1': 'プロジェクト相談',
    'about.cta.btn2': '実績を見る',

    // Services
    'services.hero.eyebrow': 'サービス内容',
    'services.hero.title': '私たちが提供\nできること。',
    'services.hero.desc': '戦略、デザイン、そして開発。ブランド構築からスケーラブルなサーバーインフラ構築まで。',
    'services.cta.title': 'プロジェクトを開始する準備はできましたか？',
    'services.cta.desc': '無料のオンラインミーティングを予約して、製品のビジョンを一緒に具体化しましょう。',
    'services.cta.btn': '無料相談を予約する',
    'services.process.eyebrow': '開発プロセス',
    'services.process.title': '仕事の\n進め方',
    'services.process.desc': 'すべての案件は、スピード、透明性、クオリティを最大化するために体系化されたフローに沿って進められます。',

    // Portfolio
    'portfolio.hero.eyebrow': '実績紹介',
    'portfolio.hero.title': 'ビジネスケーススタディと\nデジタル製品。',
    'portfolio.hero.desc': '私たちはスタートアップやグローバルブランドと提携し、美しく、高速で、成果を出すソフトウェアを構築します。',
    'portfolio.testimonials.eyebrow': 'クライアントの声',
    'portfolio.testimonials.title': 'パートナー企業\nからの評価',
    'portfolio.testimonials.desc': '単にコードを書くだけではなく、それによってクライアントが得た実質的な成果によって成功を測定します。',

    // Contact
    'contact.hero.eyebrow': 'お問い合わせ',
    'contact.hero.title': 'スタジオに\n相談する',
    'contact.hero.desc': 'デジタル体験を次のステージに進めませんか？ヒアリングシートに入力するか、スケジュールから相談枠をご予約ください。',
    'contact.info.office': 'スタジオ所在地',
    'contact.info.hours': '営業時間',
    'contact.info.hours.val': '月 – 金, 午前9時 – 午後6時',
    'contact.tabs.brief': 'ヒアリングシート',
    'contact.tabs.call': '相談枠を予約',
    'contact.form.name': 'お名前',
    'contact.form.email': 'メールアドレス',
    'contact.form.focus': 'ご相談内容',
    'contact.form.focus.placeholder': 'カテゴリを選択してください...',
    'contact.form.budget': 'ご予算（目安）',
    'contact.form.message': 'プロジェクト概要',
    'contact.form.message.placeholder': '製品の目的、ゴール、スケジュールなどを教えてください...',
    'contact.form.submit': '送信する',
    'contact.form.success.title': 'ありがとうございます！',
    'contact.form.success.desc': 'シートの送信が完了しました。担当者が内容を確認し、24時間以内にご連絡いたします。',
    'contact.form.success.btn': '別の問い合わせを送信する',
    'contact.book.timezone': 'あなたのタイムゾーン',
    'contact.book.select': '希望日時を選択',
    'contact.book.submit': '予約を確定する',
    'contact.book.success.title': '予約が確定しました！',
    'contact.book.success.desc': 'オンライン相談の予約日時は以下の通りです：',
  },
};

interface LanguageContextProps {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>('EN');

  useEffect(() => {
    const saved = localStorage.getItem('codnexa-lang') as LanguageCode;
    if (saved && LANGUAGES.some(l => l.code === saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('codnexa-lang', lang);
  };

  const t = (key: string): string => {
    const dict = translations[language] || translations.EN;
    return dict[key] || translations.EN[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return ctx;
}
